# Generated by Django 4.0.6 on 2022-07-26 12:16

import Users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='OTP',
            field=models.IntegerField(blank=True, null=True, validators=[Users.validators.length_validator], verbose_name='One Time Passcode'),
        ),
        migrations.AddField(
            model_name='user',
            name='OTP_creation_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='One Time Passcode Creation Time'),
        ),
    ]
